### ISSUE TITLE
Banned by https://archlinux.org/packages

### ISSUE THREAD

**Issue by rodrigogarcia2021** [clmbtti/mur#9]
Hi,

I am testing the script (i am not a dev and not know about python), and I added some packages more, when run it the archlinux.org server banned me. If use a VPN i can access, so is a ban.

Additionally, vulkan-headers that is flagged out of date, breaks the script.

No user agent or the speed for query maybe I guess?, well, i put here my modification:

```#!/usr/bin/env python
import subprocess
import os

PACKAGES = [
    "mesa",
    "mesa-demos",
    "vulkan-mesa-layers",
    "opencl-mesa",
    "lib32-mesa",
    "vulkan-intel",
    "vulkan-swrast",
    "mesa-vdpau",
    "libva-mesa-driver",
    "libva-vdpau-driver",
    "libva",
    "lib32-libva-vdpau-driver",
    "lib32-libva-mesa-driver",
    "lib32-mesa-demos",
    "lib32-mesa-vdpau",
    "lib32-vulkan-icd-loader",
    "lib32-vulkan-intel",
    "lib32-vulkan-radeon",
    "mesa-utils",
    "vulkan-radeon",
    "vulkan-headers",
    "vulkan-icd-loader",
    "lib32-libva",
]

ARCH = subprocess.run(["uname", "-m"], capture_output=True, text=True).stdout.strip()
URL_PREFIX = f"https://archlinux.org/packages/@REPO@/{ARCH}"
URL_SUFFIX = "download"

CACHE_DIR = f"/tmp/package_cache"

# Create the cache directory inside /tmp if it does not exist
if not os.path.exists(CACHE_DIR):
    os.makedirs(CACHE_DIR)

# Set permissions to allow the current user to create and modify files in it
os.chmod(CACHE_DIR, 0o755)

# Generate a list of package URLs using a list comprehension
PACKAGES_URL = [
    f"{URL_PREFIX.replace('@REPO@', 'multilib')}/{package}/{URL_SUFFIX}"
    if package.startswith("lib32-")
    else f"{URL_PREFIX.replace('@REPO@', 'extra')}/{package}/{URL_SUFFIX}"
    for package in PACKAGES
    if subprocess.run(["pacman", "-Qi", package], capture_output=True, text=True).returncode == 0
]

# Start the yes command in the background to automatically respond "y" to the prompt
yes_process = subprocess.Popen(["yes", "S"], stdout=subprocess.PIPE)

# Run the pacman command, using the output of the yes command as the input
subprocess.run(
    ["sudo", "pacman", "--cachedir", CACHE_DIR, "-U"] + PACKAGES_URL,
    stdin=yes_process.stdout,
)

# Terminate the yes command
yes_process.terminate()

# Delete the cache directory
subprocess.run(["rm", "-rf", CACHE_DIR])

**Comment by clmbtti** [comment]
You will need to add a one-second delay, as you are coming too hot for the server. Remember, we cannot control what arch mirror's behaviour will be once several files are demanded too quickly. They may read it as a DDoS attack.

Add to the top of your script `import time`:
```
#!/usr/bin/env python
import subprocess
import os
import time
```

And at the end, replace
```
# Run the pacman command, using the output of the yes command as the input
subprocess.run(
    ["sudo", "pacman", "--cachedir", CACHE_DIR, "-U"] + PACKAGES_URL,
    stdin=yes_process.stdout,
)
```
with:

```
# Download the packages with a delay between each download
for package_url in PACKAGES_URL:
    subprocess.run(["sudo", "pacman", "--cachedir", CACHE_DIR, "-U", package_url], stdin=yes_process.stdout)
    time.sleep(1)  # Pause for 1 second before continuing
```

Other than that, make sure all those packages are accessible in the path and consider removing those who aren't. I tested it on a VM and the request for one of those packages returned 404 for me. 
Hope this helps you.

**Comment by rodrigogarcia2021** [comment]
> You will need to add a one-second delay, as you are coming too hot for the server. Remember, we cannot control what arch mirror's behaviour will be once several files are demanded too quickly. They may read it as a DDoS attack.
> 
> Add to the top of your script `import time`:
> 
> ```
> #!/usr/bin/env python
> import subprocess
> import os
> import time
> ```
> 
> And at the end, replace
> 
> ```
> # Run the pacman command, using the output of the yes command as the input
> subprocess.run(
>     ["sudo", "pacman", "--cachedir", CACHE_DIR, "-U"] + PACKAGES_URL,
>     stdin=yes_process.stdout,
> )
> ```
> 
> with:
> 
> ```
> # Download the packages with a delay between each download
> for package_url in PACKAGES_URL:
>     subprocess.run(["sudo", "pacman", "--cachedir", CACHE_DIR, "-U", package_url], stdin=yes_process.stdout)
>     time.sleep(1)  # Pause for 1 second before continuing
> ```
> 
> Other than that, make sure all those packages are accessible in the path and consider removing those who aren't. I tested it on a VM and the request for one of those packages returned 404 for me. Hope this helps you.

Thank you very much.

yes, the package vulkan-headers is flagged as out of date, then the script can't download it (but using firefox i can)

I added 4 seconds, just in case.

**Comment by clmbtti** [comment]
You are most welcome! I hope we find a better solution soon.

**Comment by clmbtti** [comment]
Closed. The script has in its scope only the download of a minimal set of necessary packages.

**Comment by rodrigogarcia2021** [comment]
> You are most welcome! I hope we find a better solution soon.

I hope too, because I am reading a lot of people migrating to others arch based. For now, you save me the day and the month probably :+1:
